version: 2
registries:
  redhat-registry:
    type: docker-registry
    url: https://registry.access.redhat.com
    username: ${{secrets.REDHAT_USERNAME}}
    password: ${{secrets.REDHAT_PASSWORD}}

updates:
  - package-ecosystem: "docker"
    directory: "/"  # Path to your Dockerfile(s)
    registries:
      - redhat-registry
    schedule:
      interval: "daily"
    # Optional: Focus only on Red Hat images
