version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - redhat
    reviewers:
      - "MajidEM"
registries:
  type: "docker-registry"
  url: "registry.redhat.io"
  username: "${{ secrets.REDHAT_USERNAME }}"
  password: "${{ secrets.REDHAT_PASSWORD }}"
